In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8480, 2989, 2113, 3949],
 [8480, 2989, 2113, 7841],
 [8480, 219, 2113, 2684],
 [7026, 5095, 5136, 6383, 734],
 [7026, 5095, 5136, 6383, 1488],
 [7410, 8480, 2244, 2113, 8022],
 [4542, 1136, 9381, 6383]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8480 2989 2113 3949]
 [   0    0    0    0 8480 2989 2113 7841]
 [   0    0    0    0 8480  219 2113 2684]
 [   0    0    0 7026 5095 5136 6383  734]
 [   0    0    0 7026 5095 5136 6383 1488]
 [   0    0    0 7410 8480 2244 2113 8022]
 [   0    0    0    0 4542 1136 9381 6383]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

c:\Users\indira gothi\Downloads\simple_rnn_imdb\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.build(input_shape=(None, sent_length))

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[[-4.24776226e-03, -2.82332432e-02, -2.17218287e-02,
         -2.14452744e-02, -2.60914918e-02, -4.64191549e-02,
         -2.79215332e-02, -2.58343704e-02, -1.19743459e-02,
          1.18217953e-02],
        [-4.24776226e-03, -2.82332432e-02, -2.17218287e-02,
         -2.14452744e-02, -2.60914918e-02, -4.64191549e-02,
         -2.79215332e-02, -2.58343704e-02, -1.19743459e-02,
          1.18217953e-02],
        [-4.24776226e-03, -2.82332432e-02, -2.17218287e-02,
         -2.14452744e-02, -2.60914918e-02, -4.64191549e-02,
         -2.79215332e-02, -2.58343704e-02, -1.19743459e-02,
          1.18217953e-02],
        [-4.24776226e-03, -2.82332432e-02, -2.17218287e-02,
         -2.14452744e-02, -2.60914918e-02, -4.64191549e-02,
         -2.79215332e-02, -2.58343704e-02, -1.19743459e-02,
          1.18217953e-02],
        [-4.23885509e-03, -2.92120706e-02,  4.64598089e-03,
          1.67110823e-02,  1.57668255e-02, -3.00696846e-02,
          2.97243334e-02,  4.40856107e-02, -4.399683

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 8480, 2989, 2113, 3949], dtype=int32)

In [20]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


array([[[-0.00424776, -0.02823324, -0.02172183, -0.02144527,
         -0.02609149, -0.04641915, -0.02792153, -0.02583437,
         -0.01197435,  0.0118218 ],
        [-0.00424776, -0.02823324, -0.02172183, -0.02144527,
         -0.02609149, -0.04641915, -0.02792153, -0.02583437,
         -0.01197435,  0.0118218 ],
        [-0.00424776, -0.02823324, -0.02172183, -0.02144527,
         -0.02609149, -0.04641915, -0.02792153, -0.02583437,
         -0.01197435,  0.0118218 ],
        [-0.00424776, -0.02823324, -0.02172183, -0.02144527,
         -0.02609149, -0.04641915, -0.02792153, -0.02583437,
         -0.01197435,  0.0118218 ],
        [-0.00423886, -0.02921207,  0.00464598,  0.01671108,
          0.01576683, -0.03006968,  0.02972433,  0.04408561,
         -0.04399684, -0.00494797],
        [ 0.0297252 ,  0.02710852,  0.03060949,  0.03185612,
          0.04063847, -0.02888392,  0.04069084,  0.04620533,
         -0.0230682 ,  0.04019315],
        [ 0.01429101, -0.04832108,  0.00735547, -0.0